services:
  webapp:
    build: ./go
    environment:
      ISUCON_DB_HOST: 127.0.0.1
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
      PPROTEIN_HTTPLOG: /home/isucon/webapp/logs/access.log
      PPROTEIN_SLOWLOG: /home/isucon/webapp/logs/slow.log
    network_mode: host
    volumes:
      - /home/isucon/webapp/tenant_db:/home/isucon/webapp/tenant_db
      - /home/isucon/webapp/sql:/home/isucon/webapp/sql
      - /home/isucon/webapp/public.pem:/home/isucon/webapp/public.pem:ro
      - /home/isucon/initial_data:/home/isucon/initial_data
      - /home/isucon/tmp:/home/isucon/tmp
      - /var/log/nginx/access.log:/home/isucon/webapp/logs/access.log:ro
      - /var/log/mysql/mysql-slow.log:/home/isucon/webapp/logs/slow.log:ro
    init: true
    command: sh -c "go run ./cmd/isuports/main.go"
